# SOPS configuration for encrypted manifests in this repository.
# Replace age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg with your own age public recipient
# (starts with "age1...") before encrypting secrets.
creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    encrypted_regex: '^(data|stringData)$'
    age:
      - age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
