apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sidero-system
resources:
  - namespace.yaml
  - infrastructure-provider.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: sidero
    literals:
      - SIDERO_CONTROLLER_MANAGER_API_ENDPOINT=10.0.0.1
      - SIDERO_CONTROLLER_MANAGER_AUTO_ACCEPT_SERVERS=true
      - SIDERO_CONTROLLER_MANAGER_AUTO_BMC_SETUP=false
      - SIDERO_CONTROLLER_MANAGER_DEPLOYMENT_STRATEGY=Recreate
      - SIDERO_CONTROLLER_MANAGER_DISABLE_DHCP_PROXY=false
      - SIDERO_CONTROLLER_MANAGER_HOST_NETWORK=true
      - SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT=10.0.0.1