apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/ingress-nginx/v1.12.0/
patches:
  - target:
      kind: Service
      name: ingress-nginx-controller
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: replace
        path: /spec/externalTrafficPolicy
        value: Local
