apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: gateway
spec:
  secretName: gateway-tls
  issuerRef:
    kind: ClusterIssuer
    name: homelab
  dnsNames:
    - argocd.homelab.ntbc.io
    - argoworkflows.homelab.ntbc.io
    - dex.homelab.ntbc.io
    - grafana.homelab.ntbc.io
    - prometheus.homelab.ntbc.io
    - alertmanager.homelab.ntbc.io
