apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chrony
  namespace: argocd
spec:
  destination:
    namespace: chrony
    server: https://kubernetes.default.svc
  project: management
  source:
    path: overlay/management/chrony
    repoURL: git@github.com:Nosmoht/homelab-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
