apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-dcgm-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nvidia-dcgm-exporter
    name: homelab
  project: management
  source:
    chart: dcgm-exporter
    repoURL: https://nvidia.github.io/gpu-monitoring-tools/helm-charts
    targetRevision: 2.4.0
    helm:
      valuesObject:
        serviceMonitor:
          enabled: true
          interval: 15s
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: feature.node.kubernetes.io/pci-0300_10de.present
                      operator: In
                      values:
                        - "true"
                - matchExpressions:
                    - key: feature.node.kubernetes.io/pci-10de.present
                      operator: In
                      values:
                        - "true"
                - matchExpressions:
                    - key: nvidia.com/gpu.present
                      operator: In
                      values:
                        - "true"
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
