apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workload-fleet
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  sourceRepos:
    - https://github.com/Nosmoht/homelab-apps.git
  destinations:
    - server: "*"
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
