apiVersion: dnsmasq.kvaps.cf/v1beta1
kind: DhcpOptions
metadata:
  name: homelab
spec:
  controller: homelab
  options:
    - key: option:router
      values: [10.0.0.1]
    - key: option:dns-server
      values: [10.0.0.1]
  # - key: option:ntp-server
  #   values: [10.0.0.1]
    - key: option:domain-name
      values: [homelab.ntbc.io]
    - key: option:domain-search
      values: [homelab.ntbc.io]
