apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dnsmasq-controller
resources:
  - namespace.yaml
  - ../../../base/dnsmasq-controller/v0.6.0
  - daemonset.yaml
  - dhcp-options.yaml
  - dhcp-hosts.yaml
  - dnsmasq-options.yaml
  - dns-hosts.yaml
