apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-argocd-bridge-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capi-argocd-bridge-secret-reader
subjects:
  - kind: ServiceAccount
    name: capi-argocd-bridge
    namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capi-argocd-bridge-secret-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capi-argocd-bridge-secret-writer
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-argocd-bridge-secret-writer
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: capi-argocd-bridge
    namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capi-argocd-bridge-secret-writer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capi-argocd-bridge-workflow-submit
  namespace: argo-events
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-argocd-bridge-workflow-submit
  namespace: argo-events
subjects:
  - kind: ServiceAccount
    name: capi-argocd-bridge
    namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capi-argocd-bridge-workflow-submit
