apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age
            optional: true
      initContainers:
        - name: install-ksops
          image: quay.io/getsops/sops:v3.11.0-alpine
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -euo pipefail
              arch="$(uname -m)"
              case "${arch}" in
                aarch64|arm64) ksops_arch="arm64" ;;
                x86_64|amd64) ksops_arch="x86_64" ;;
                *)
                  echo "unsupported architecture: ${arch}" >&2
                  exit 1
                  ;;
              esac
              url="https://github.com/viaduct-ai/kustomize-sops/releases/download/v4.4.0/ksops_4.4.0_Linux_${ksops_arch}.tar.gz"
              wget -qO- "${url}" | tar -xz -C /custom-tools ksops
              cp "$(command -v sops)" /custom-tools/sops
              chmod +x /custom-tools/ksops /custom-tools/sops
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
      containers:
        - name: argocd-repo-server
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /sops-age/keys.txt
          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin/ksops
              subPath: ksops
            - name: custom-tools
              mountPath: /usr/local/bin/sops
              subPath: sops
            - name: sops-age
              mountPath: /sops-age
              readOnly: true
