apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: argocd-secret-sso-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./argocd-secret-sso.sops.yaml
