apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    oidc.dex.clientSecret: ENC[AES256_GCM,data:iocLdiNUZPbdaP+SZE21eT4LcYM8J1ftVD2mTe/AOOgKPA8Z7Ifdq1/3nbgT+gqsZu0lSMEQCJZpNQPykSB0Rw==,iv:oF0vMGm2TurJGw9e3SXOlTMfpdASKY9NJPu0tXc0flg=,tag:MLVGDhCwRqBX+VYdDTbyZQ==,type:str]
sops:
    age:
        - recipient: age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc1RFeUhKbnBrTjFxY3Ba
            cXZwZjQrblM0bHprSkhqd2tQcU9nTDRzRmdzCmlnUnVSRkwvajgxZGcxb29XaURr
            YmYxTjFWcTlNeDhaSVlxT1V2cjRMYTAKLS0tIDVUU2NHZFEzUkNOQ1phMlcwMlkw
            MWRuZEQvdGhZTEpsMWVVSjdkNnVBYVUKNjLlSq7CmmvW6/ji0VjOWT5ewSOYoGkB
            rAuukIZAcfli33KLs12Q2RUMjPsOP7G1nDDo7yhWCxj54XTqyskNaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T17:13:46Z"
    mac: ENC[AES256_GCM,data:g5lVG6w+Xr61Zp3mxETH9DdvmIdEVQcD+FZODnerxTg+XEd0mubPu3O5hxTSjggV4snp22f0dkfvjWUc3mWjN3cKLmZ6bBzPltjp+Jg22tGT0CAMOsrntxpbr0a9/dK3wrWhRrtD4DioMzPpL7f4xP9qzyPlDAzGF0AQRkfuf4c=,iv:6VUX1STcKbLAMBd6WIHAvo3IZoHWRp6hLQ4tyJ4Q5IA=,tag:MS4CNdW7dughnoFJ1AiBsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
