apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    oidc.dex.clientSecret: ENC[AES256_GCM,data:Xi+8OQ5N/Z9FvmLbs1orYE2tbfQzDT8dHj+G0YdX/ZaPY24kT5hH+S6ATVFUzLqqPDlEbKBM4xo/fpVvnLEd1Q==,iv:z/YjS284zvj5p3Kzz99HclBWxYTizDZ8/4U5tLOPS5g=,tag:8ZASHYiXrfa/z0mMUqTufA==,type:str]
sops:
    age:
        - recipient: age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb1B5L3I4bXZFS2wzWmhR
            T1Rtcnk1QmlqK2VnL01RM0N0SkE0em5IVGp3ClhvYXduTXk0WUE3aStjeWU0RHhP
            NlFZaXNrdzNNWUwvMUczMHJUY0ZqSk0KLS0tIFZHTGl1UmlKNmN3SWJ5ditBaFVD
            aStKWmlsUGxJbWRiMmcvU2dacTdOU2MKL6Eohm4CzZtYY10ZZ7cNUaWzZjnldC2K
            LyCCNXuacxZbYxiHHz04LW2m9nKfPTI0Hs1IjISf7D0hNpYLCcWirQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T16:00:43Z"
    mac: ENC[AES256_GCM,data:Btt2RonNxvBvd8DMzM4FoZYbO9oPD4UELAwHrl/uRKsqjK6LFBid8b6JzSMIVNcnLDesoQ0VaQTyEBwNe60nQj0wdXYHFu7fkgf/hp0nLhFWyicc95IaI9G8JjK5LcywjmjFzIWIybDcjLlCG5aIIiVoFJhByG1mTJqdUqikvY8=,iv:QsaTj349HFOoKylOyQ85lVQPnZieaIhV2dwBOuLArs8=,tag:fAp/HYPMqaKWaIOwN6NKAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
