apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      initContainers:
        - name: copyutil
          args:
            - /bin/sh
            - -c
            - |
              set -euo pipefail
              rm -f /var/run/argocd/argocd /var/run/argocd/argocd-cmp-server
              /bin/cp /usr/local/bin/argocd /var/run/argocd/argocd
              /bin/ln -sf /var/run/argocd/argocd /var/run/argocd/argocd-cmp-server
