apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-tls
  namespace: dex
spec:
  secretName: dex-tls
  dnsNames:
    - dex.homelab.ntbc.io
  issuerRef:
    kind: ClusterIssuer
    name: homelab
