apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: dex-oidc-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./dex-oidc-secrets.sops.yaml
