apiVersion: v1
kind: Secret
metadata:
    name: dex-oidc-secrets
    namespace: dex
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    google-client-id: ENC[AES256_GCM,data:VtNELWmrfgi5ODvRmE7S82x+LVlZge01kksHKJHy6e+yieuRJQlDwvoY+ofrNd2L+QM/jMXzgqNQVwU9Xbh/tjbajPDJam7h,iv:5Iqgld/vuUsgPnHkh8Eam7fxe8YvMFWo3YntEEmOLCM=,tag:8cyA4iCsVGizc6r9omm+QA==,type:str]
    google-client-secret: ENC[AES256_GCM,data:VVn1JjFRmIntoT8PzpD3rLdPACAySyZn+D9tU7QpCCIWY0E=,iv:r4GYxnlPufINCMe79PpMUzoFD7TnAFWIcPpwjwDlwEY=,tag:TfXYgUcA/wD0UOF/+hJftg==,type:str]
    argocd-oidc-client-secret: ENC[AES256_GCM,data:l8jq6Kb2wFpqOEGGy0nOKaAf/Js3a1oNLh5R0Yol5JYCPoSR+GyYkDoAuErJzVaBKviqz3ROi3OHJu/mQRW0MQ==,iv:13LaWQtODmYThbPwpKTpBjyj4XzPK4043udpF2erTp0=,tag:89bzfSi2qO6J6cN2h4OLZQ==,type:str]
    argo-workflows-oidc-client-secret: ENC[AES256_GCM,data:Quf6KalyHU3zfl8OdKEjzwR66ydbhj4bNJ7o7UOKJ4osglh9kwnBlMl2/wolEOb+8IzkvzROHqhkmHeX0KHHMg==,iv:Xbm3UqqgmqiMMe8XeaRckzz0xoYqH1uP30d4sGSGBdM=,tag:9eQCiXeY7a5z/o/lC5oO9Q==,type:str]
sops:
    age:
        - recipient: age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWTIzS1BOOTlibEhFUWZy
            TXovSmRBVS9jcmR0R01kRm5QTXNmcXR4dEhNCnVkaytUcFV3cGtzQVczM2M2alVU
            eWdldTd3Ujk2MkljYXVuRHh6ZFp4Um8KLS0tIG9GNHRFanVjb1krQzZIMmhOR251
            SEVrczBDVklWdE0rWXl0VE5paUwwMWsK5dDHwIre8BPECbSt4923sZDlDGWIjMLv
            qJKsR43N12huj/FFAcv9yfcEJWvTtgtnRuTfk6JZP3+J6FDQeLqKBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T16:00:43Z"
    mac: ENC[AES256_GCM,data:WoDQgDi2EJ6WSokIK4RYwhxk6AZpzCNNXuTLHDFBqgafJGU2+VF2TqVB5VnA4AyGyvr8FgecCMfi7HSxbLqSybDD+IC6aW2zN1+vWLPe3MPNuJogjqftG8/gqQ7rpXWMdDyPmqsl7SmuPGyUSNr1titefeTCcaFhScekhQ8E6A8=,iv:aQkuphvEqmU1bS/Jn5eULqRwyBBqTF7Ot1WDH8gwbrI=,tag:nk0oOV3wXFb3tJ2b+PerBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
