apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: homelab-cp-i5
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha2
        kind: ServerClass
        name: homelab-cp-i5
        namespace: default
