apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: homelab-cp-i5
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  strategicPatches:
    - |
      machine:
        install:
          disk: /dev/sda
  environmentRef:
    namespace: default
    name: homelab-compute
  qualifiers:
    hardware:
      - compute:
          processors:
            - productName: Intel(R) Core(TM) i5-7400T CPU @ 2.40GHz
---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: homelab-compute-slow
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  strategicPatches:
    - |
      machine:
        install:
          disk: /dev/sda
  environmentRef:
    namespace: default
    name: homelab-compute
  qualifiers:
    hardware:
      - compute:
          processors:
            - productName: Intel(R) Core(TM) i3-6100T CPU @ 3.20GHz
        system:
          family: ThinkCentre M710q
          manufacturer: LENOVO
---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: homelab-compute-medium
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  strategicPatches:
    - |
      machine:
        install:
          disk: /dev/sda
  environmentRef:
    namespace: default
    name: homelab-compute
  qualifiers:
    hardware:
      - compute:
          processors:
            - productName: Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz
---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: homelab-compute-fast
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  strategicPatches:
    - |
      machine:
        install:
          disk: /dev/sda
  environmentRef:
    namespace: default
    name: homelab-compute
  qualifiers:
    hardware:
      - compute:
          processors:
            - productName: Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz
        system:
          family: ThinkCentre M910q
          manufacturer: LENOVO
---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: homelab-compute-gpu
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  strategicPatches:
    - |
      machine:
        install:
          disk: /dev/sda
  environmentRef:
    namespace: default
    name: homelab-gpu
  qualifiers:
    hardware:
      - compute:
          processors:
            - productName: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
