apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  version: v1.9.3
  manifestPatches:
    - |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: capi-controller-manager
        namespace: capi-system
      spec:
        template:
          spec:
            containers:
              - name: manager
                image: registry.k8s.io/cluster-api/cluster-api-controller:v1.9.3
                imagePullPolicy: IfNotPresent
                command:
                  - /manager
                args:
                  - --leader-elect
                  - --diagnostics-address=:8443
                  - --insecure-diagnostics=false
                  - --feature-gates=MachinePool=true,ClusterResourceSet=true,ClusterTopology=false,RuntimeSDK=false,MachineSetPreflightChecks=true,MachineWaitForVolumeDetachConsiderVolumeAttachments=true
                env:
                  - name: POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.name
                  - name: POD_UID
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.uid
                ports:
                  - containerPort: 9443
                    name: webhook-server
                    protocol: TCP
                  - containerPort: 9440
                    name: healthz
                    protocol: TCP
                  - containerPort: 8443
                    name: metrics
                    protocol: TCP
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /healthz
                    port: healthz
                    scheme: HTTP
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 1
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /readyz
                    port: healthz
                    scheme: HTTP
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 1
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                  privileged: false
                  runAsGroup: 65532
                  runAsUser: 65532
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                  - mountPath: /tmp/k8s-webhook-server/serving-certs
                    name: cert
                    readOnly: true
