#!/usr/bin/env bash
set -euo pipefail

CERT_MANAGER_DIR="overlay/management/cert-manager"
KUSTOMIZATION_FILE="${CERT_MANAGER_DIR}/kustomization.yaml"
ISSUER_FILE="${CERT_MANAGER_DIR}/cluster-issuer.yaml"
DOC_FILE="docs/cert-manager.md"
GITIGNORE_FILE="${CERT_MANAGER_DIR}/.gitignore"
SECRET_FILE="${CERT_MANAGER_DIR}/service-account-key.json"

fail() {
  echo "[FAIL] $1" >&2
  exit 1
}

for file in "$KUSTOMIZATION_FILE" "$ISSUER_FILE" "$DOC_FILE" "$GITIGNORE_FILE"; do
  [ -f "$file" ] || fail "Missing required file: $file"
done

# Secret material must never be tracked in git.
if git ls-files --error-unmatch "$SECRET_FILE" >/dev/null 2>&1; then
  fail "$SECRET_FILE must not be committed"
fi

rg -q '^service-account-key\.json$' "$GITIGNORE_FILE" || \
  fail "$GITIGNORE_FILE must ignore service-account-key.json"

# Secret must be provided out-of-band, not generated by Kustomize.
if rg -q '^secretGenerator:' "$KUSTOMIZATION_FILE"; then
  fail "$KUSTOMIZATION_FILE must not use secretGenerator"
fi

if rg -q 'service-account-key\.json' "$KUSTOMIZATION_FILE"; then
  fail "$KUSTOMIZATION_FILE must not reference service-account-key.json"
fi

for pattern in \
  'name: homelab' \
  'name: homelab-staging' \
  'name: google-cloud-dns' \
  'key: service-account-key.json' \
  'dnsZones:' \
  '- homelab.ntbc.io'
do
  rg -q --fixed-strings -- "$pattern" "$ISSUER_FILE" || \
    fail "$ISSUER_FILE is missing: $pattern"
done

rg -q 'create secret generic google-cloud-dns' "$DOC_FILE" || \
  fail "$DOC_FILE must document secret creation"

rg -q 'get secret google-cloud-dns' "$DOC_FILE" || \
  fail "$DOC_FILE must document secret health-check"

echo "cert-manager secret health checks passed"
