apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab
spec:
  acme:
    email: thomas.krahn.tk@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: homelab-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudDNS:
            project: io-ntbc-domain-control-1900413
            serviceAccountSecretRef:
              key: service-account-key.json
              name: google-cloud-dns
