apiVersion: v1
kind: Secret
metadata:
    name: argo-workflows-sso-oidc
    namespace: argo
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:PiLWnwwc2VBvAulz1iU=,iv:6VjG1wxWlbCrwfUBOE/TFDBwTLrLphDgK81gvucxO9c=,tag:d+79RSWA6adjBI0foBLIGQ==,type:str]
    client-secret: ENC[AES256_GCM,data:ZZgyisk0c9fVDyANrn6TnCX363VpBVdX6QxUpT+aoV/bGOhGg2KykYrRaAgvWgvSusxY9HFPGcVx0UDBEL+1Xw==,iv:aTowlMgDHq+ksM/YvYXfTo2iF7/cTDIn1crQpNsTXQo=,tag:Ib8E4nYGUldTdiaGojLHpg==,type:str]
sops:
    age:
        - recipient: age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobEIzVHRPY2tVbHJpYTdK
            blZHM1k3c0xyMFBWTldiZGtDNXpDTUZSbXdzCnV0NGxWT1FieVZOSG5rRVZOUlFy
            RmtqSldSYzhXLy92LzBLQ2dUVU9WNDgKLS0tIDEvYkpNdGV0TXhnaGJjYlFsQXNY
            S01BNm1FZW13VlJDb3l2Qjh2V1ZWMWsK4aBkngq/kQb7xUvfqOvQ21di48LqwSs0
            szlNZCxFZFm0W2/VUj39J307HUW+pElTSvnnJAgkaKYj9X7QfvB2rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T16:38:15Z"
    mac: ENC[AES256_GCM,data:ktfpqsKzgMcHlWhBqvquDxbbUwgYdtqpGCQm8B6lLY01WbaRtwQeWSlGcr1ab8fmse75Fy/lbirPDCRMApt4w4uhpeMIContayblc07wNRrKYjCDnrIT9sPXjbl13IXy/WBk11YV7CRWzr9ohS7PCVlpcbPk+9rQB3CVnnycoqQ=,iv:O9GCW4eLXAaxi6RqIewBeMPjKB/99MnRkgVaH6C3u8I=,tag:kbiE7yntSrN+8jvvAu3QZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
