apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: argo-workflows-sso-oidc-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./argo-workflows-sso-oidc.sops.yaml
