apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sso-admin
  namespace: argo
  annotations:
    workflows.argoproj.io/rbac-rule: "email == 'sso-admin@example.com' || sub == 'sso-admin@example.com'"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso-admin.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-workflows-sso-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-sso-admin
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sso-admin
    namespace: argo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sso-readonly
  namespace: argo
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso-readonly.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-workflows-sso-readonly
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-sso-readonly
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sso-readonly
    namespace: argo
